# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02690466e49907a5ca4508359c50f449a0e50ec65c0a0a3be1233612c6f4f92b1a083ae83add3ecdef61f472654783488c3da8dc5ad96f268d78c20bb95f15e8

test:
  secret_key_base: 7e8df37da956763496f86826d039b03bfb1a06c20e581f1d31dd65a8b30dfedb7b627980f2776c2010c7efd807812cd623e2de2c89053e220296d2b8c91499ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
